### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by ananchev** [coder-alpha/FMoviesPlus.bundle#35]
Can you explain how the download option is supposed to work?
I have a movie in Queued - Started with 0%  for few days now. Not sure if it is my setup, or something not working.

**Comment by JamminR** [comment]
Do you have phantomjs and cryptolibrary binaries installed? (I don't have crypto, it's only good for mega).
If not, see the Fmovies Wiki section "##Binary files installation" - https://github.com/coder-alpha/FMoviesPlus.bundle/wiki
Also in that wiki at the top is the 'discussion thread link', it's likely better for asking questions like this, as technically, your is more a question on 'how' than it is a 'it's determined to be broken' at this time.

**Comment by coder-alpha** [comment]
@ananchev There might be a bug that got introduced in the last version if you tried doing the Download via the FMovies interface rather than choosing from the Download Sources list. I'm kinda in the middle of redoing some of the Download section code so I don't have that version to confirm.

I'd recommend just removing that one and re-adding it choosing one from the Download Sources list.

**Comment by ananchev** [comment]
@JamminR  -  PhantomJS is installed and working well. You are right topic is more on 'how' - I missed the discussion thread - good to know for future. 
@coder-alpha  - I will try what you say and let you know.

**Comment by ananchev** [comment]
Here confirm choosing from Download Sources works for the same file.

**Comment by coder-alpha** [comment]
Fixed in ver. 0.73. Thanks @ananchev
