### ISSUE TITLE
RapidVideo

### ISSUE THREAD

**Issue by aconer81** [coder-alpha/FMoviesPlus.bundle#49]
Hey I'm having an issue with playing rapidvideo links they used to work fine but all of a sudden now an X appears next to the rapidvideo links instead of a V which means its enabled and playable and I have checked in interface options then external host and it shows that rapidvideo is enabled so dunno what issue could be thanks 4 any feedback other than that great plugin & much appreciate the work

**Comment by Oldpapa** [comment]
Simple answer if it broken use external links. They could be offline or being blocked.It can become an uncertain connection any time.

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 6, 2018 at 6:42 AM, aconer81<notifications@github.com> wrote:   
Hey I'm having an issue with playing rapidvideo links they used to work fine but all of a sudden now an X appears next to the rapidvideo links instead of a V which means its enabled and playable and I have checked in interface options then external host and it shows that rapidvideo is enabled so dunno what issue could be thanks 4 any feedback other than that great plugin & much appreciate the work

**Comment by coder-alpha** [comment]
Rapidvideo seems to have removed captcha, so it should be working fine now. If they re-implement it will see if there is a fix for it.
