### ISSUE TITLE
Error when playing video

### ISSUE THREAD

**Issue by AleDema** [coder-alpha/FMoviesPlus.bundle#55]
Whenever I try to play a video from Openload, Rapidvideo or Streamango, I get this error: 

Video Unavailable. Error: {u'message': u'preg_match(): Delimiter must not be alphanumeric or backslash', u'code': u'0', u'type': u'ErrorException'}

I already manually reinstalled the plugin and installed PhantomJS

EDIT: streaming works if I select the video from external source, but shows error if i select it in the main directory

**Comment by coder-alpha** [comment]
If this a new install I suggest trying a PMS restart. If you manually updated by overwriting the plugin, I suggest trying a clean install by closing Plex, deleting the bundle and then copy over the bundle. And then do a PMS restart.

I checked and OpenLoad & Streamango work fine. Rapidvideo can have issues sometimes due to captcha authentication now.

**Comment by AleDema** [comment]
I already tried doing everything you listed but unfortunately the issue hasn't been fixed, if i click on the video from here: https://gyazo.com/d8bd3d499f06554c59eb764301eddc49
It shows the error

**Comment by faizygr8** [comment]
I have the Same Issue Did you manage to Fix that?

**Comment by coder-alpha** [comment]
Typically due to installation issues. Recommend using 7zip for unzipping the downloaded zip. Please attached zip of log files with debug enabled from the Channel Prefs. if issue persists.
