### ISSUE TITLE
Video playback errors

### ISSUE THREAD

**Issue by bigwheels98** [coder-alpha/FMoviesPlus.bundle#69]
I have been having all kinds of issues playing anything thru a web browser (firefox v.66 or chrome v.74 with cache disabled ) and thru my plex-firetv client in several instances.  I have cleared cache, reset cookies, done re-installs several times and I am not sure what else I should do?  The recaptcha still says not active so im not sure if it's no longer needed or what?  So i did a factory reset, cleared the plugin cache, cleared the data off the plex fire app and turned on Plex debugging.  Just tried running Avengers Age of Ultron didn't work on either chrome (playback error) or fire tv (transcoding error).  Earlier I got Rocketeer to play on fire tv using external sources at 720 but failed on firefox.  Anyway, I have the needed logs, but im kinda a noob so i may not have gotten everything.  If not I'll gladly do it over.

[com.plexapp.plugins.fmoviesplus.log](https://github.com/coder-alpha/FMoviesPlus.bundle/files/3189040/com.plexapp.plugins.fmoviesplus.log)
[com.plexapp.plugins.fmoviesplus.log.zip](https://github.com/coder-alpha/FMoviesPlus.bundle/files/3189041/com.plexapp.plugins.fmoviesplus.log.zip)

**Comment by JamminR** [comment]
At this time, Coder-alpha and the rest of us regular users recommend only using External sources.
Ensure you are on latest version of FMP.
 if you've not been checking the discussion thread here over the past month or two (though not required, definitely recommended), I'd recommend seeing this current post regarding current state of affairs
#33 (comment)

Fmovies sites have been heavily engaged in preventing viewers (such as us) using Kodi/Plex plugins/other tools that bypass actual use of a web browser to view their sites, including captchas, and now, IP banning.
@coder-alpha has been doing what he can, but some things just overly difficult, so for now, he/we recommend using the external listings searches and sites instead of the 'whats hot' type menus.
And of course, ensure you have the latest FMP installed, as he's done great work in adding external (to non-working Fmovies site) search capabilities

As such, slower sites with less bandwidth may not allow playback as easily as the Fmovies sites.

**Comment by bigwheels98** [comment]
That's the issue none of the external sources are working for me!!  Every little step I have read in the discussion thread hasn't made any difference.  I'm not trying to be difficult and I fully appreciate the hard, time consuming work that @coder-alpha has put into this project.  I was just hoping a quick review of my logs might lead to a more generalized solution for everyone.  But holding back a few weeks until the next version might be the best bet.

**Comment by coder-alpha** [comment]
External Sources via External Listing and Search (search results with an *), NOT via the FMovies menu. I don't see anywhere in the log where you seem to have done that.

![image](https://user-images.githubusercontent.com/10291660/57906323-8e7bcd00-7847-11e9-8cf2-c23b3d36af19.png)


Also, make sure your External Providers are enabled.
![image](https://user-images.githubusercontent.com/10291660/57906244-53799980-7847-11e9-94b9-f3a64f25808b.png)

**Comment by bigwheels98** [comment]
Ok i found the cyrodome and phantomjs weren't installed correctly, they have now been enabled however the openload.js says the OS is not defined in externals.py.  Could that be my issue?  I'm still getting the error but my last attempt i received a transcoder conversion error. 

![image](https://user-images.githubusercontent.com/50718571/57944146-a67d3c00-789b-11e9-93de-4e5b606193e9.png)

**Comment by JamminR** [comment]
When browsing, are you only using the "External Listing" menu?
When searching, are you only trying results with a "* in front of the name.
Example image below, the external search results start after "wargames". If I tried Wargames, it may not play if fmovies site decided to ban my IP for whatever reason it detects foul play.
![image](https://user-images.githubusercontent.com/3392170/57961605-1ad8cf00-78de-11e9-844b-f1b995a0e797.png)

> openload.js says the OS is not defined in externals.py. Could that be my issue?

No. That's a generic error that has no impact. (Reference - https://github.com/coder-alpha/FMoviesPlus.bundle/issues/33#issuecomment-488962819 - see coder alpha's answer to 2old2fix with same question)

"Transcoder conversion error" is a Plex server or client error. Something in the video/audio container stream that Plex doesn't like. Very little, if anything, FMP code can do to fix that (I say little, because I believe it's possible FMP attempts to tell Plex 'this stream from this random site uses this information', and FMP may have been told wrong from the site, so tells plex wrong. I could be totally wrong in that guess, which then puts it 100% at Plex not understanding or the external provider content being corrupt.

**Comment by bigwheels98** [comment]
Yea i have done everything correctly so i tried other plugins both commercial and third-party and found the same video playback error.  It must be a problem with my current plex setup or the server build itself
