### ISSUE TITLE
Not able to watch on Plex retro.....It's gone :(

### ISSUE THREAD

**Issue by rdudeja1133** [coder-alpha/FMoviesPlus.bundle#70]

**Comment by JamminR** [comment]
Plex Retro no longer exists - [Reference](https://forums.plex.tv/t/eol-for-plex-retro-for-roku/412106)
You'll need to use another Plex client on Roku, such as [RarFlix](https://github.com/ljunkie/rarflix) until Roku stops the old code base it's written in , or find another device to watch FMP+ until such time Plex [ends plug-in support on servers](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/).
Closing this issue, as it is in no way due to FMP+ code.
